/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const VerAside: (typeof import('@versakit/ui'))['VerAside']
  const VerAvatar: (typeof import('@versakit/ui'))['VerAvatar']
  const VerBacktop: (typeof import('@versakit/ui'))['VerBacktop']
  const VerBadge: (typeof import('@versakit/ui'))['VerBadge']
  const VerButton: (typeof import('@versakit/ui'))['VerButton']
  const VerCard: (typeof import('@versakit/ui'))['VerCard']
  const VerCarousel: (typeof import('@versakit/ui'))['VerCarousel']
  const VerCarouselItem: (typeof import('@versakit/ui'))['VerCarouselItem']
  const VerCol: (typeof import('@versakit/ui'))['VerCol']
  const VerCollapse: (typeof import('@versakit/ui'))['VerCollapse']
  const VerCollapseItem: (typeof import('@versakit/ui'))['VerCollapseItem']
  const VerContainer: (typeof import('@versakit/ui'))['VerContainer']
  const VerDialog: (typeof import('@versakit/ui'))['VerDialog']
  const VerDivider: (typeof import('@versakit/ui'))['VerDivider']
  const VerDrawer: (typeof import('@versakit/ui'))['VerDrawer']
  const VerEmpty: (typeof import('@versakit/ui'))['VerEmpty']
  const VerFlex: (typeof import('@versakit/ui'))['VerFlex']
  const VerFooter: (typeof import('@versakit/ui'))['VerFooter']
  const VerGradientText: (typeof import('@versakit/ui'))['VerGradientText']
  const VerHeader: (typeof import('@versakit/ui'))['VerHeader']
  const VerIcon: (typeof import('@versakit/ui'))['VerIcon']
  const VerInput: (typeof import('@versakit/ui'))['VerInput']
  const VerLink: (typeof import('@versakit/ui'))['VerLink']
  const VerMain: (typeof import('@versakit/ui'))['VerMain']
  const VerMessage: (typeof import('@versakit/ui'))['VerMessage']
  const VerNotification: (typeof import('@versakit/ui'))['VerNotification']
  const VerPanel: (typeof import('@versakit/ui'))['VerPanel']
  const VerProgress: (typeof import('@versakit/ui'))['VerProgress']
  const VerRadio: (typeof import('@versakit/ui'))['VerRadio']
  const VerResult: (typeof import('@versakit/ui'))['VerResult']
  const VerRow: (typeof import('@versakit/ui'))['VerRow']
  const VerSegmented: (typeof import('@versakit/ui'))['VerSegmented']
  const VerSlider: (typeof import('@versakit/ui'))['VerSlider']
  const VerSwitch: (typeof import('@versakit/ui'))['VerSwitch']
  const VerTab: (typeof import('@versakit/ui'))['VerTab']
  const VerTable: (typeof import('@versakit/ui'))['VerTable']
  const VerTag: (typeof import('@versakit/ui'))['VerTag']
  const VerText: (typeof import('@versakit/ui'))['VerText']
  const VerTextarea: (typeof import('@versakit/ui'))['VerTextarea']
  const VerTooltip: (typeof import('@versakit/ui'))['VerTooltip']
}
