/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VerButton: typeof import('@versakit/ui')['VerButton']
    VerCard: typeof import('@versakit/ui')['VerCard']
    VerInput: typeof import('@versakit/ui')['VerInput']
    VerSwitch: typeof import('@versakit/ui')['VerSwitch']
  }
}
